TEX    := latex
BIB    := bibtex
PDFTEX := pdflatex
PDF    := dvipdf

all:
	$(PDFTEX) ttsp_2013
	$(BIB) ttsp_2013
	$(PDFTEX) ttsp_2013
	$(PDFTEX) ttsp_2013
	$(PDFTEX) ttsp_2013

tex:
	$(PDFTEX) ttsp_2013
